# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WCFTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.6'
  # Pods for WCFTest

  target 'WCFTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WCFTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
